### ISSUE TITLE
color issue

### ISSUE THREAD

**Issue by collinsmarra** [ctron/patternfly-yew-quickstart#12]
I am new to yew. I found this library while trying to create a sidebar...
It looks awesome. But I think there is something I am missing
Like I am able to display the button but not the color

![image](https://user-images.githubusercontent.com/48761741/216896011-b86d8a95-fff3-4426-9301-f4501fa1112d.png)

**Comment by ctron** [comment]
The button has different "variants", which follow the concepts of PatternFly (which again follows the idea of others). Those variants are e.g. "primary", "secondary", … which then get styled using different colors.

**Comment by collinsmarra** [comment]
I figured that out. Thanks
