### ISSUE TITLE
SideNavs

### ISSUE THREAD

**Issue by collinsmarra** [ctron/patternfly-yew-quickstart#13]
I am new to UI and yew, so I am trying different things. 
So I am trying to create a sidenav  and my code looks like this

![image](https://user-images.githubusercontent.com/48761741/217523640-899d2e4c-be39-4db9-b074-8aae4ca64742.png)

the output looks like this
![image](https://user-images.githubusercontent.com/48761741/217523791-5a1c8afb-7db6-4e6d-964b-6fa99fcfdd5c.png)

My expectation was that they would align on the left vertically.

What am I missing?

**Comment by ctron** [comment]
You are missing a `Page`, which has the `sidebar` property. You can take a look at the PatternFly documentation: https://www.patternfly.org/v4/components/page Even though there is now "yew" section, it should map pretty straight forward to Rust/Yew in many cases.

**Comment by collinsmarra** [comment]
works like charm. Thank you
