### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by HythamSoliman** [ctron/patternfly-yew-quickstart#8]
With yew, while trying to use the Badge component, it generate the below error.
almost done for each tag i tried!
I am using the master yew from github

the trait bound `yew::functional::FunctionComponent<patternfly_yew::badge::badge>: yew::Component` is not satisfied
the following other types implement trait `yew::Component`:
  ContextProvider<T>
  InputComponent
  MyPage
required because of the requirements on the impl of `BaseComponent` for `yew::functional::FunctionComponent<patternfly_yew::badge::badge>`rustc[E0277](https://doc.rust-lang.org/error-index.html#E0277)
login_page.rs(116, 9): Error originated from macro call here

**Comment by ctron** [comment]
Which version of yew are you using?
