### ISSUE TITLE
build not successful

### ISSUE THREAD

**Issue by SirVer** [ctron/patternfly-yew-quickstart#9]
Trying to build this repo as described in the readme gives build errors for me:

```
Error: Undefined operation "div(div(1px, 1px), 16) * 1rem".
   ╷
12 │   @return div(pf-strip-unit($pxval), $base) * 1rem;
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/@patternfly/patternfly/sass-utilities/functions.scss 12:11       pf-size-prem()
  node_modules/@patternfly/patternfly/sass-utilities/scss-variables.scss 94:30  @import
  node_modules/@patternfly/patternfly/sass-utilities/_all.scss 5:9              @import
  node_modules/@patternfly/patternfly/patternfly-addons.scss 1:9                root stylesheet
2022-10-23T19:43:20.958515Z  INFO copying directory path="node_modules/@patternfly/patternfly/assets"
```

Is this a trunk bug or what is going on here?

**Comment by ctron** [comment]
No, I think there was some deprecation in `dart-sass` at some point.

What versions of patternfly and dart-sass are you using?

I know it isn't a fix, but can you try downgrading to an older `dart-sass` version. Or upgrading patternfly. Just to see if this has an impact.

**Comment by ctron** [comment]
I went ahead and upgraded the patternfly dependency. Maybe you can re-try (without changes) and check if that fixes the issue on your side.

**Comment by SirVer** [comment]
@ctron Thanks for looking into this. It did not seem to fix my problems:

```
2022-11-02T19:27:51.380808Z  INFO finished compiling sass/scss path="assets/style.scss"
Error: Undefined operation "div(div(1px, 1px), 16) * 1rem".
   ╷
11 │   @return div(pf-strip-unit($pxval), $base) * 1rem;
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```

These are the exact commands I ran:

~~~bash
cd /tmp
git clone ctron/patternfly-yew-quickstart
cd patternfly-yew-quickstart
npm install
trunk serve
~~~

**Comment by ctron** [comment]
Hm, this is strange. Because the CI doesn't do anything different.

Can you post the version of `dart-sass` you have installed? (`sass --version`).

This was a breaking change in `dart-sass`, which introduced `div` and deprecated `/`. It looks like your `sass` version is "too old" for the `div` function: https://sass-lang.com/documentation/breaking-changes/slash-div

**Comment by SirVer** [comment]
Sorry for the long delay:

```
1.26.8 compiled with dart2js 2.8.4
```

**Comment by ctron** [comment]
Yes, I think you need to upgrade it. That seems like a "too old" version for this.
